# Generated by Django 5.2 on 2025-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='car_images/default.jpg', upload_to='car_images/'),
        ),
    ]
