# Generated by Django 5.2 on 2025-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
